export const ActionTypes = {
  SET_NFT: "SET_NFT",
  SELECTED_NFT: "SELECTED_NFT",
  REMOVE_SELECTED_NFT: "REMOVE_SELECTED_NFT",
  SET_ACCOUNT: "SET_ACCOUNT",
  SET_TOKEN_COTRACT: "SET_TOKEN_COTRACT",
  SET_MARKET_CONTRACT: "SET_MARKET_CONTRACT"
};
